trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: buildConfiguration
  value: 'Release'
- name: webAppName
  value: 'webappedusync'
- name: resourceGroup
  value: 'edusync'
- name: ASPNETCORE_ENVIRONMENT
  value: 'Production'
- name: ASPNETCORE_DETAILED_ERRORS
  value: 'true'

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
    includePreviewVersions: false
  displayName: 'Install .NET SDK'

- task: DotNetCoreCLI@2
  displayName: 'Clear NuGet cache'
  inputs:
    command: custom
    custom: nuget
    arguments: 'locals all --clear'

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    verbosityRestore: 'Detailed'

- task: DotNetCoreCLI@2
  displayName: 'Build main project'
  inputs:
    command: 'build'
    projects: '**/EduSync_Assessment.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Build test project'
  inputs:
    command: 'build'
    projects: '**/EduSync_Assessment.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/EduSync_Assessment.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish the project'
  inputs:
    command: 'publish'
    projects: '**/EduSync_Assessment.csproj'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build /p:UseAppHost=false'
    zipAfterPublish: true
    modifyOutputPath: true

- task: AzureWebApp@1
  displayName: 'Deploy to Azure Web App'
  inputs:
    azureSubscription: 'AzureConnection'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
    appSettings: '-ASPNETCORE_ENVIRONMENT Production -ASPNETCORE_DETAILED_ERRORS true -WEBSITE_ENABLE_SYNC_UPDATE_SITE true'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container' 