trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- name: buildConfiguration
  value: 'Release'
- name: webAppName
  value: 'webappedusync'
- name: resourceGroup
  value: 'edusync'
- name: ASPNETCORE_ENVIRONMENT
  value: 'Production'
- name: ASPNETCORE_DETAILED_ERRORS
  value: 'true'

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
  displayName: 'Install .NET SDK'

- script: |
    ls -la
    pwd
    dotnet restore
  displayName: 'Restore Dependencies'

- script: |
    dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build .NET Project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'
  displayName: 'Run Tests'

- script: |
    dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory) --no-build
  displayName: 'Publish .NET Project'

- script: |
    echo "Checking published artifact directory: $(Build.ArtifactStagingDirectory)"
    ls -la $(Build.ArtifactStagingDirectory)
  displayName: 'Verify Published Files'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'AzureConnection'
    appType: 'webApp'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)'
    deploymentMethod: 'auto'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container' 